process_names:
  - comm:
    - nginx
    - apache2
    - prometheus
    - k3s-agent
    - promtail
    - containerd
    - speaker
    - containerd-shim
    - longhorn-manage
    - longhorn-instan
    - longhorn
    - iscsid
    - mysqld
    - telegraf
    - influxd
    - udisksd
    - grafana
    - usb-storage
    - loki
    - process-exporte
    - csi-snapshotter
    - csi-provisioner
    - nginx-ingress-c
  - name: "exporters"
    cmdline:
    - '/usr/local/bin/.+[_-]exporter'
  - name: "{{.Username}} processes"
    cmdline:
    - '.+'