apiVersion: v1
kind: Service
metadata:
  name: frontend-loki-app01
  labels:
    app.kubernetes.io/name: frontend-loki-app01
spec:
  ports:
  - name: frontend-loki-app01
    port: 3100
    protocol: TCP
    targetPort: 3100
  selector:
    app.kubernetes.io/name: frontend-loki-app01
  sessionAffinity: None
  clusterIP: None
  type: ClusterIP
  publishNotReadyAddresses: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-loki-app01
  labels:
    app.kubernetes.io/name: frontend-loki-app01
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-loki-app01
  labels:
    app.kubernetes.io/name: frontend-loki-app01
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend-loki-app01
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend-loki-app01
    spec:
      containers:
      - args:
        - -config.file=/etc/loki/config.yaml
        image: grafana/loki:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: 1500Mi
            cpu: "2"
          requests:
            memory: 1000Mi
            cpu: "0.25"
        name: frontend-loki-app01
        ports:
        - containerPort: 3100
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/loki
          name: configmap-loki-config01
        - mountPath: /data
          name: frontend-loki-app01
        - mountPath: /tmp
          name: tmp
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      restartPolicy: Always
      terminationGracePeriodSeconds: 4800
      volumes:
      - configMap:
          defaultMode: 420
          name: configmap-loki-config01
        name: configmap-loki-config01
      - name: frontend-loki-app01
        persistentVolumeClaim:
          claimName: frontend-loki-app01
      - emptyDir: {}
        name: tmp