apiVersion: builtin
kind: LabelTransformer
metadata:
  name: metadata-labels
labels:      # kustomize
  environment : operatins
  app.kubernetes.io/managed-by: github
  app.kubernetes.io/created-by: controller-manager
fieldSpecs:  # kustomize
- path: metadata/labels
  create: true
- path: spec/selector/matchLabels
  kind: Deployment
  create: true
- path: spec/template/metadata/labels
  kind: Deployment
  create: true