apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: testing-monitoring
namePrefix: testing-monitoring-
nameSuffix: "-001"
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: kustomize-password
  files:
  - password=password.txt
  - token=token.txt
configMapGenerator:
- name: configmap-telegraf-config01
  files:
  - telegraf.conf
- name: configmap-grafana-config01
  files:
  - grafana.ini
- name: configmap-alertmanager-config01
  files:
  - alertmanager-config.yaml