apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
namePrefix: monitoring-
nameSuffix: "-001"
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: kustomize-secret
  files:
  - password=password.txt
  - token-telegraf=token-telegraf.txt
  - token-slack=token-slack.txt
- name: kustomize-secret-minio
  files:
  - minio_root_user=minio_root_user.txt
  - minio_root_password=minio_root_password.txt