apiVersion: 1
datasources:
  - access: proxy
    orgId: 1
    basicAuth: false
    editable: true
    isDefault: true
    name: loki
    type: loki
    uid: loki
    url: http://monitoring-frontend-loki-read01-001:3100
    version: 1

  - access: proxy
    orgId: 1
    basicAuth: false
    editable: true
    isDefault: false
    name: prometheus
    type: prometheus
    uid: prometheus
    url: http://monitoring-backend-prometheus-db01-001:9090
    version: 1

  - access: proxy
    orgId: 1
    basicAuth: false
    editable: true
    isDefault: false
    name: Mimir
    type: prometheus
    uid: mimir
    url: http://monitoring-backend-prometheus-db01-001:9090
    version: 1
  
  - access: proxy
    orgId: 1
    basicAuth: false
    editable: true
    isDefault: false
    name: InfluxDB
    type: influxdb
    uid: influxdb
    url: http://monitoring-backend-influxdb-db01-001:8086
    version: 1

  - access: proxy
    orgId: 1
    basicAuth: false
    editable: true
    isDefault: false
    name: Alertmanager
    type: alertmanager
    uid: alertmanager
    url: http://monitoring-backend-alertmanager01-001:9093
    version: 1
