auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  http_server_read_timeout: 60s
  http_server_write_timeout: 60s
  grpc_server_max_recv_msg_size: 33554432
  grpc_server_max_send_msg_size: 33554432
  log_level: info

common:
  path_prefix: /data/loki
  replication_factor: 1
  ring:
    kvstore:
      store: memberlist

memberlist:
  join_members: 
    - monitoring-frontend-loki-read01-001.monitoring.svc.cluster.local:7946
    - monitoring-frontend-loki-write01-001.monitoring.svc.cluster.local:7946

storage_config:
  filesystem:
    directory: /data/loki/share/chunks
  tsdb_shipper:
    active_index_directory: /data/loki/share/tsdb-index
    cache_location: /data/loki/share/tsdb-cache
    shared_store: filesystem

chunk_store_config:
  max_look_back_period: 2184h

schema_config:
  configs:
    - from: 2023-09-08
      index:
        period: 24h
        prefix: index_
      object_store: filesystem
      schema: v12
      store: tsdb

limits_config:
  ingestion_rate_mb: 8
  ingestion_burst_size_mb: 16
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  enforce_metric_name: false
  per_stream_rate_limit: 5MB
  per_stream_rate_limit_burst: 15MB
  max_query_length: 2165h
  max_query_lookback: 90d
  max_cache_freshness_per_query: '10m'
  split_queries_by_interval: 15m
  max_query_parallelism: 32

frontend:
  max_outstanding_per_tenant: 4096
  compress_responses: true
  log_queries_longer_than: 20s

querier:
  max_concurrent: 20

query_range:
  split_queries_by_interval: 24h
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

query_scheduler:
  max_outstanding_requests_per_tenant: 4096

compactor:
  working_directory: /data/loki/share/compactor
  shared_store: filesystem

ingester:
  chunk_block_size: 262144
  chunk_idle_period: 1h
  chunk_target_size: 1048576
  chunk_retain_period: 30s
  max_chunk_age: 1h 
  max_transfer_retries: 0

ingester_client:
  remote_timeout: 30s
  grpc_client_config:
    max_send_msg_size: 33554432
    max_recv_msg_size: 33554432

ruler:
  wal:
    dir: /data/loki/ruler-wal
  storage:
    type: local
    local:
      directory: /data/loki/rules
  rule_path: /data/loki/scratch
  alertmanager_url: "http://${NAMESPACE}-backend-alertmanager01-001:9093"
  enable_alertmanager_v2: true
  remote_write:
    enabled: true
    client:
      url: "http://${NAMESPACE}-backend-prometheus-db01-001:9090/api/v1/write"
  ring:
    kvstore:
      store: memberlist
  enable_api: true
  enable_sharding: true