server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://${NAMESPACE}-frontend-loki-write01-headless-001:3100/loki/api/v1/push
scrape_configs:
- job_name: kubernetes-pods-app
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - target_label: __service__
    source_labels: [__meta_kubernetes_pod_label_app]
  - target_label: __host__
    source_labels: [__meta_kubernetes_pod_node_name]
  - action: replace
    separator: /
    replacement: $1
    target_label: job
    source_labels: [__meta_kubernetes_namespace, __service__]
  - action: replace
    source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - action: replace
    target_label: pod_name
    source_labels: [__meta_kubernetes_pod_name]
  - action: replace
    target_label: container_name
    source_labels: [__meta_kubernetes_pod_container_name]
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  - target_label: __path__
    separator: /
    replacement: /var/log/pods/*$1/*.log
    source_labels: [__meta_kubernetes_pod_uid, __meta_kubernetes_pod_container_name]
  pipeline_stages:
  - regex:
      expression: '^(?P<timestamp>\S+)\s+\S+\s+\S+\s+(?P<remote_addr>\S+) - - \[(?P<time_local>[^\]]+)\] "(?P<request>\S+ \S+ \S+)" (?P<status>\d{3}) (?P<body_bytes_sent>\d+) "-" "(?P<http_user_agent>[^"]+)" (?P<request_id>\S+) (?P<upstream_response_time>\S+) \[(?P<upstream_name>[^\]]+)\] \[\] (?P<upstream_addr>\S+) (?P<bytes_sent>\d+) (?P<request_time>\S+) (?P<upstream_status>\d+) (?P<proxy_session_id>\S+)$'
  - labels:
      remote_addr:
      status:
      request:
      upstream_addr:
      request_time:
      upstream_status:
      http_user_agent:
      request_id:
  - timestamp:
      source: time_local
      format: 02/Jan/2006:15:04:05 -0700
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      node: ${HOSTNAME}
      __path__: /var/log/*log
- job_name: dmesg
  static_configs:
  - targets:
      - localhost
    labels:
      job: dmesg
      node: ${HOSTNAME}
      __path__: /var/log/dmesg
- job_name: messages
  static_configs:
  - targets:
      - localhost
    labels:
      job: messages
      node: ${HOSTNAME}
      __path__: /var/log/messages
- job_name: journal
  journal:
    json: false
    max_age: 12h
    path: /var/log/journal
    labels:
      job: "journal"
  relabel_configs:
    - source_labels: ['__journal__hostname']
      target_label: 'host'
    - source_labels:
      - __journal__systemd_unit
      target_label: systemd_unit
    - source_labels:
      - __journal_priority
      target_label: level
  pipeline_stages:
  - template:
      source: level
      template: '{{ if eq .Value "0" }}{{ Replace .Value "0" "emerg" 1 }}{{ else if eq .Value "1" }}{{ Replace .Value "1" "alert" 1 }}{{ else if eq .Value "2" }}{{ Replace .Value "2" "crit" 1 }}{{ else if eq .Value "3" }}{{ Replace .Value "3" "err" 1 }}{{ else if eq .Value "4" }}{{ Replace .Value "4" "warning" 1 }}{{ else if eq .Value "5" }}{{ Replace .Value "5" "notice" 1 }}{{ else if eq .Value "6" }}{{ Replace .Value "6" "info" 1 }}{{ else if eq .Value "7" }}{{ Replace .Value "7" "debug" 1 }}{{ end }}'
  - labels:
      level: