auth_enabled: false


server:
  http_listen_port: 3100


common:
  path_prefix: /data/loki
  storage:
    filesystem:
      chunks_directory: /data/loki/chunks
      rules_directory: /data/loki/rules
  
  replication_factor: 1


  ring:
    kvstore:
      store: memberlist

storage_config:
  tsdb_shipper:
    active_index_directory: /data/loki/tsdb-index
    cache_location: /data/loki/tsdb-cache
    shared_store: filesystem

schema_config:
  configs:
    - from: 2023-09-09
      index:
        period: 24h
        prefix: index_
      object_store: filesystem
      schema: v12
      store: tsdb


ruler:
  wal:
    dir: /data/loki/ruler-wal
  storage:
    type: local
    local:
      directory: /data/loki/rules
  rule_path: /data/loki/scratch
  alertmanager_url: "http://${NAMESPACE}-backend-alertmanager01-001:9093"
  enable_alertmanager_v2: true
  remote_write:
    enabled: true
    client:
      url: "http://${NAMESPACE}-backend-prometheus-db01-001:9090/api/v1/write"
  ring:
    kvstore:
      store: memberlist
  enable_api: true
  enable_sharding: true