process_names:
  - comm:
    - alertmanager
    - argocd-applicat
    - argocd-dex
    - argocd-notifica
    - argocd-repo-ser
    - argocd-server
    - consul
    - consul-k8s-cont
    - containerd
    - containerd-shim
    - controller
    - coredns
    - csi-attacher
    - csi-node-driver
    - csi-provisioner
    - csi-resizer
    - csi-snapshotter
    - dockerd
    - grafana
    - jupyter-lab
    - k3s-agent
    - k3s-server
    - livenessprobe
    - local-path-prov
    - loki
    - longhorn
    - longhorn-instan
    - longhorn-manage
    - metrics-server
    - ModemManager
    - mysqld
    - nginx
    - nginx-ingress-c
    - node_exporter
    - polkitd
    - process-exporte
    - promtail
    - rngd
    - rsyslogd
    - speaker
    - systemd-timesyn
    - telegraf
    - tgtd
    - vault
    - vault-k8s
    - webhook
    - workflow-contro