auth_enabled: false

server:
  http_listen_address: 0.0.0.0
  grpc_listen_address: 0.0.0.0
  http_listen_port: 3100
  grpc_listen_port: 9095
  http_server_read_timeout: 600s
  http_server_write_timeout: 600s
  grpc_server_max_recv_msg_size: 33554432
  grpc_server_max_send_msg_size: 33554432
  log_level: info

memberlist:
  join_members: 
    - ${NAMESPACE}-frontend-loki-memberlist01-headless-001.${NAMESPACE}.svc.cluster.local:7946
  dead_node_reclaim_time: 30s
  gossip_to_dead_nodes_time: 15s
  left_ingesters_timeout: 30s
  bind_addr: ['0.0.0.0']
  bind_port: 7946
  gossip_interval: 2s

common:
  compactor_address: http://${NAMESPACE}-frontend-loki-write01-headless-001.${NAMESPACE}.svc.cluster.local:3100
  storage:
    s3:
      endpoint: http://${NAMESPACE}-minio-loki-01-001.${NAMESPACE}.svc.cluster.local:9000
      access_key_id: ${MINIO_ROOT_USER}
      secret_access_key: ${MINIO_ROOT_PASSWORD}
      insecure: true
      bucketnames: loki
      s3forcepathstyle: true
      
storage_config:
  tsdb_shipper:
    active_index_directory: /data/loki/tsdb-index
    cache_location: /data/loki/tsdb-cache
    shared_store: s3

schema_config:
  configs:
  - from: 2023-07-11
    store: tsdb
    object_store: s3
    schema: v12
    index:
      prefix: index_
      period: 24h

chunk_store_config:
  max_look_back_period: 336h

limits_config:
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  enforce_metric_name: false
  per_stream_rate_limit: 5MB
  per_stream_rate_limit_burst: 15MB
  max_query_length: 2165h
  max_cache_freshness_per_query: '10m'
  max_query_parallelism: 32
  split_queries_by_interval: 15m

frontend:
  max_outstanding_per_tenant: 4096
  compress_responses: true
  log_queries_longer_than: 20s

querier:
  max_concurrent: 20
  query_ingesters_within: 2h

query_range:
  parallelise_shardable_queries: false
  split_queries_by_interval: 0
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

query_scheduler:
  max_outstanding_requests_per_tenant: 4096

compactor:
  working_directory: /loki/loki/compactor
  shared_store: s3
  compactor_ring:
    kvstore:
      store: memberlist

ingester:
  chunk_idle_period: 1m
  lifecycler:
    join_after: 10s
    observe_period: 5s
    ring:
      replication_factor: 3
      kvstore:
        store: memberlist
    final_sleep: 0s
  wal:
    enabled: true
    dir: /data/loki/wal
  chunk_block_size: 524288
  chunk_target_size: 1572864
  chunk_retain_period: 30s
  chunk_encoding: snappy
  max_chunk_age: 1h
  max_transfer_retries: 0
  flush_op_timeout: 10s

ruler:
  alertmanager_url: "http://${NAMESPACE}-backend-alertmanager01-001.${NAMESPACE}.svc.cluster.local:9093"
  enable_alertmanager_v2: true
  enable_api: true
  enable_sharding: true
  wal:
    dir: /data/loki/ruler-wal
  storage:
    type: local
    local:
      directory: /data/loki/rules
  rule_path: /loki/rules-temp
  remote_write:
    enabled: true
    clients:
      local:
         url: http://${NAMESPACE}-backend-prometheus-db01-001.${NAMESPACE}.svc.cluster.local:9090/api/v1/write
         queue_config:
           capacity: 1
           batch_send_deadline: 0s
  ring:
    kvstore:
      store: memberlist
