server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://monitoring-frontend-loki-write01-001:3100/loki/api/v1/push
scrape_configs:
- job_name: kubernetes-pod
  kubernetes_sd_configs:
    - role: pod
  relabel_configs:
    - action: replace
      target_label: host_pod
      source_labels: [__meta_kubernetes_pod_node_name]
    - action: replace
      source_labels: [__meta_kubernetes_namespace]
      target_label: namespace
    - action: replace
      target_label: pod_name
      source_labels: [__meta_kubernetes_pod_name]
    - action: replace
      target_label: container_name
      source_labels: [__meta_kubernetes_pod_container_name]
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - target_label: __path__
      separator: /
      replacement: /var/log/pods/*$1/*.log
      source_labels: [__meta_kubernetes_pod_uid, __meta_kubernetes_pod_container_name]
  pipeline_stages:
    - regex:
        expression: '^(?P<timestamp>[^ ]+) (?P<stream>stderr|stdout) .*'
    - labels:
        stream:
    - match:
        selector: '{app_kubernetes_io_name="ingress-nginx"}'
        stages:
          - regex:
              expression: '^\S+\s+(stdout|stderr)\s+\S+\s+(?P<remote_addr>\S+).*HTTP/\d\.\d"\s(?P<http_status>\d{3})'
          - labels:
              remote_addr:
              http_status:
          - timestamp:
              source: timestamp
              format: 02/Jan/2006:15:04:05 -0700
    - match:
        selector: '{namespace="nginx-proxy"}'
        stages:
          - regex:
              expression: '^(?P<timestamp>\S+)\s+(?P<stream>stdout|stderr)\s+\S+\s+(?P<remote_addr>\S+).+\s"(?P<method>\S+)\s(?P<path>\S+)\s(?P<protocol>[^"]+)"\s(?P<http_status>\d{3})\s'
          - labels:
              remote_addr:
              http_status:
          - timestamp:
              source: time_local
              format: 02/Jan/2006:15:04:05 -0700
    - match:
        selector: '{namespace="haproxy", app="haproxy"}'
        stages:
          - cri: {}
          - regex:
              expression: '^(?P<client_ip>\S+):\d+ \[(?P<timestamp>\d{2}/\w{3}/\d{4}:\d{2}:\d{2}:\d{2}\.\d{3})\] (?P<frontend>\S+) (?P<backend>[^/]+)/(?P<server>\S+) .*'
          - labels:
              client_ip:
              frontend:
              backend:
              server:
          - timestamp:
              source: timestamp
              format: 02/Jan/2006:15:04:05.000
              location: Asia/Tokyo
- job_name: journal
  journal:
    json: true
    max_age: 12h
    path: /var/log/journal
    labels:
      job: "journal"
  relabel_configs:
    - source_labels: ['__journal__hostname']
      target_label: 'host'
    - source_labels: ['__journal__systemd_unit']
      target_label: systemd_unit
    - source_labels: ['__journal_priority']
      target_label: level
  pipeline_stages:
    - template:
        source: level
        template: '{{ if eq .Value "0" }}{{ Replace .Value "0" "emerg" 1 }}{{ else if eq .Value "1" }}{{ Replace .Value "1" "alert" 1 }}{{ else if eq .Value "2" }}{{ Replace .Value "2" "crit" 1 }}{{ else if eq .Value "3" }}{{ Replace .Value "3" "err" 1 }}{{ else if eq .Value "4" }}{{ Replace .Value "4" "warning" 1 }}{{ else if eq .Value "5" }}{{ Replace .Value "5" "notice" 1 }}{{ else if eq .Value "6" }}{{ Replace .Value "6" "info" 1 }}{{ else if eq .Value "7" }}{{ Replace .Value "7" "debug" 1 }}{{ end }}'
    - labels:
        level: