auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /data/loki
  storage:
    filesystem:
      chunks_directory: /data/loki/chunks
      rules_directory: /data/loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: memberlist

storage_config:
  tsdb_shipper:
    shared_store: filesystem

chunk_store_config:
  max_look_back_period: 2184h

schema_config:
  configs:
    - from: 2023-09-08
      index:
        period: 24h
        prefix: index_
      object_store: filesystem
      schema: v12
      store: tsdb

limits_config:
  ingestion_rate_mb: 8
  ingestion_burst_size_mb: 16
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  enforce_metric_name: false
  per_stream_rate_limit: 5MB
  per_stream_rate_limit_burst: 15MB
  max_query_length: 2165h
  max_query_lookback: 90d
  max_cache_freshness_per_query: '10m'

frontend:
  max_outstanding_per_tenant: 32768
  compress_responses: true
  log_queries_longer_than: 20s

querier:
  max_concurrent: 20

query_range:
  split_queries_by_interval: 0
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

query_scheduler:
  max_outstanding_requests_per_tenant: 32768

compactor:
  working_directory: /data/loki/compactor
  shared_store: filesystem

ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
  chunk_block_size: 262144
  chunk_idle_period: 1h
  chunk_target_size: 1048576
  chunk_retain_period: 30s
  max_chunk_age: 1h 
  max_transfer_retries: 0

ingester_client:
  remote_timeout: 30s
  grpc_client_config:
    max_send_msg_size: 33554432
    max_recv_msg_size: 33554432

ruler:
  wal:
    dir: /data/loki/ruler-wal
  storage:
    type: local
    local:
      directory: /data/loki/rules
  rule_path: /data/loki/scratch
  alertmanager_url: "http://${NAMESPACE}-backend-alertmanager01-001:9093"
  enable_alertmanager_v2: true
  remote_write:
    enabled: true
    client:
      url: "http://${NAMESPACE}-backend-prometheus-db01-001:9090/api/v1/write"
  ring:
    kvstore:
      store: memberlist
  enable_api: true
  enable_sharding: true