groups:
- name: on_premises
  rules:
  - alert: InstanceDown
    expr: up == 0
    labels:
      severity: warning
    annotations:
      summary: "Instance {{ $labels.instance }}/{{ $labels.job }} target down"
      description: "{{ $labels.instance }}の{{ $labels.job }}Jobが停止しています"
