---
apiVersion: v1
kind: Service
metadata:
  name: backend-prometheus-db01
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: prometheus
  ports:
  - name: prometheus
    port: 9090
    targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-prometheus-db01
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  template:
    metadata:
      name: backend-prometheus-db01
      labels:
        app.kubernetes.io/name: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
      - name: backend-prometheus-db01
        image: backend-prometheus-db01
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        args:
        - --config.file=/mnt/prometheus/config-prometheus.yaml
        - --web.enable-remote-write-receiver
        - --enable-feature=remote-write-receiver
        ports:
        - containerPort: 9090
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: INFLUXDB_TOKEN
          valueFrom:
            secretKeyRef:
              name: kustomize-secret
              key: token-telegraf
        volumeMounts:
        - name: configmap-prometheus-volume01
          mountPath: /mnt/prometheus/
        - name: data-volume
          mountPath: /mnt/data/
        - name: secrets-volume
          mountPath: /var/run/secrets
      volumes:
      - name: configmap-prometheus-volume01
        projected:
          sources:
          - configMap:
              name: configmap-prometheus-config01
          - configMap:
              name: configmap-prometheus-config02
      - name: data-volume
        emptyDir: {}
      - name: secrets-volume
        hostPath:
          path: /var/run/secrets