version: 2.1
orbs: 
  kubernetes: circleci/kubernetes@1.3.0

workflows:
  testing:
    jobs:
      - create-update:
          context: kaniko
          filters:
            branches:
              only: 
                - main
      - status-pod:
          context: kaniko
          requires:
            - create-update
          filters:
            branches:
              only: 
                - main
      - status-frontend-grafana:
          context: kaniko
          requires:
            - status-pod
          filters:
            branches:
              only: 
                - main
      - status-backend-grafana:
          context: kaniko
          requires:
            - status-pod
          filters:
            branches:
              only: 
                - main
      - status-frontend-loki:
          context: kaniko
          requires:
            - status-pod
          filters:
            branches:
              only: 
                - main
      - status-backend-prometheus:
          context: kaniko
          requires:
            - status-pod
          filters:
            branches:
              only: 
                - main
      - status-backend-influxdb:
          context: kaniko
          requires:
            - status-pod
          filters:
            branches:
              only: 
                - main
      - status-backend-telegraf:
          context: kaniko
          requires:
            - status-pod
          filters:
            branches:
              only: 
                - main
      - status-backend-promtail:
          context: kaniko
          requires:
            - status-pod
          filters:
            branches:
              only: 
                - main
      - status-backend-alertmanager:
          context: kaniko
          requires:
            - status-pod
          filters:
            branches:
              only: 
                - main
      - delete:
          context: kaniko
          requires:
            - status-frontend-grafana
            - status-backend-grafana
            - status-frontend-loki
            - status-backend-prometheus
            - status-backend-influxdb
            - status-backend-telegraf
            - status-backend-promtail
            - status-backend-alertmanager
          filters:
            branches:
              only: 
                - main

executors:
  default:
    docker:
      - image: 'cimg/base:stable'
commands:
  setup_kubectl:
    steps:
      - run:
          name: "kubectl install"
          command: |
              curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.24.0/bin/linux/arm64/kubectl
              chmod +x ./kubectl
              sudo mv ./kubectl /usr/local/bin/kubectl
              kubectl version --client
  setup_kubeconfig:
    steps:
      - run:
          name: "kubeconfig"
          command: |
              mkdir -p ~/.kube/
              echo -n "${KUBECONFIG_DATA}" | base64 -d > ~/.kube/config
              kubectl config use-context ${CONTEXT_NAME}

jobs:
  create-update:
    resource_class: abeyuki/circleci
    executor:
      name: default
    steps:
      - checkout
      - setup_kubectl
      - setup_kubeconfig
      - kubernetes/create-or-update-resource:
          kustomize: true
          resource-file-path: overlay/testing
          show-kubectl-command: true

  status-pod:
    resource_class: abeyuki/circleci
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: status-pod
          command: |
            ns=testing-monitoring
            count=15
            i=1
            while [ $i -ne 10 ];do 
                if [[ $(kubectl get pods -n $ns --field-selector=status.phase=Running | awk 'NR>1 {print $3}' | wc -l) -ge ${count} ]] ;then 
                  echo "Count $i pod status OK" ; sleep 10 ; break
                else
                  echo "Count $i pod status NG" ; sleep 5
                fi
            done

  status-frontend-grafana:
    resource_class: abeyuki/circleci
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: status-frontend-grafana
          command: |
            ns=testing-monitoring
            app=$(kubectl get pod --selector="app.kubernetes.io/name=grafana,environment=testing" -n $ns | awk 'NR>1{print $1}' | head -1)
            if [[ $(kubectl -n $ns exec pod/${app} -- grafana-server -v | awk '{print $1,$2}') = "Version 8.5.2" ]] ;then
              echo "ps status OK" 
            else
              echo "ps status NG" ; break
            fi

  status-backend-grafana:
    resource_class: abeyuki/circleci
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: status-backend-grafana
          command: |
            ns=testing-monitoring
            app=$(kubectl get pod --selector="app.kubernetes.io/name=mariadb-grafana,environment=testing" -n $ns | awk 'NR>1{print $1}' | head -1)
            if [[ $(kubectl -n $ns exec pod/${app} --  mysql --version | awk '{print $1,$2,$3,$4,$5}') = "mysql Ver 15.1 Distrib 10.5.16-MariaDB," ]] ;then
              echo "ps status OK" 
            else
              echo "ps status NG" ; break
            fi

  status-frontend-loki:
    resource_class: abeyuki/circleci
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: status-frontend-loki
          command: |
            ns=testing-monitoring
            app=$(kubectl get pod --selector="app.kubernetes.io/name=frontend-loki-app01,environment=testing" -n $ns | awk 'NR>1{print $1}' | head -1)
            if [[ $(kubectl -n $ns exec pod/${app} -- sh -c 'loki -version | sed -e 2,5d  | sed  -e s/\(.*//') = "loki, version 2.4.1" ]] ;then
              echo "ps status OK" 
            else
              echo "ps status NG" ; break
            fi

  status-backend-prometheus:
    resource_class: abeyuki/circleci
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: status-backend-prometheus
          command: |
            ns=testing-monitoring
            app=$(kubectl get pod --selector="app.kubernetes.io/name=prometheus,environment=testing" -n $ns | awk 'NR>1{print $1}' | head -1)
            if [[ $(kubectl -n $ns exec pod/${app} -- sh -c 'prometheus --version | sed -e 2,5d  | sed  -e s/\(.*//') = "prometheus, version 2.36.2" ]] ;then
              echo "ps status OK" 
            else
              echo "ps status NG" ; break
            fi

  status-backend-influxdb:
    resource_class: abeyuki/circleci
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: status-backend-influxdb
          command: |
            ns=testing-monitoring
            app=$(kubectl get pod --selector="app.kubernetes.io/name=influxdb,environment=testing" -n $ns | awk 'NR>1{print $1}' | head -1)
            if [[ $(kubectl -n $ns exec pod/${app} -- influx ping ) -eq OK  ]] ;then
              echo "ps status OK" 
            else
              echo "ps status NG" ; break
            fi

  status-backend-telegraf:
    resource_class: abeyuki/circleci
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: status-backend-telegraf
          command: |
            ns=testing-monitoring
            app=$(kubectl get pod --selector="app.kubernetes.io/name=telegraf,environment=testing" -n $ns | awk 'NR>1{print $1}' | head -1)
            if [[ $(kubectl -n $ns exec pod/${app} -- telegraf --version | awk '{print $1,$2}') = "Telegraf 1.22.3"  ]] ;then
              echo "ps status OK" 
            else
              echo "ps status NG" ; break
            fi

  status-backend-promtail:
    resource_class: abeyuki/circleci
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: status-backend-promtail
          command: |
            ns=testing-monitoring
            app=$(kubectl get pod --selector="app.kubernetes.io/name=promtail,environment=testing" -n $ns | awk 'NR>1{print $1}' | head -1)
            if [[ $(kubectl -n $ns exec pod/${app} -- promtail -version | grep promtail | awk '{print $2,$3}') = "version 2.5.0" ]] ;then
              echo "ps status OK" 
            else
              echo "ps status NG" ; break
            fi

  status-backend-alertmanager:
    resource_class: abeyuki/circleci
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: status-backend-alertmanager
          command: |
            ns=testing-monitoring
            app=$(kubectl get pod --selector="app.kubernetes.io/name=alertmanager,environment=testing" -n $ns | awk 'NR>1{print $1}' | head -1)
            if [[ $(kubectl -n $ns exec pod/${app} -- alertmanager --version | grep alertmanager | awk '{print $2,$3}') = "version 0.24.0" ]] ;then
              echo "ps status OK" 
            else
              echo "ps status NG" ; break
            fi

  status-backend-node-exporter:
    resource_class: abeyuki/circleci
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: status-backend-node-exporter
          command: |
            ns=testing-monitoring
            app=$(kubectl get pod --selector="app.kubernetes.io/name=node-exporter,environment=testing" -n $ns | awk 'NR>1{print $1}' | head -1)
            if [[ $(kubectl -n $ns exec pod/${app} -- node-exporter --version | grep node_ exporter | awk '{print $2,$3}') = "version 1.3.1" ]] ;then
              echo "ps status OK" 
            else
              echo "ps status NG" ; break
            fi

  delete:
    resource_class: abeyuki/circleci
    executor:
      name: default
    steps:
      - checkout
      - setup_kubectl
      - setup_kubeconfig
      - kubernetes/delete-resource:
          kustomize: true
          now: true
          resource-file-path: overlay/testing
          wait: true