---
apiVersion: v1
kind: Service
metadata:
  name: backend-prometheus-db01
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
  - name: prometheus
    port: 9090
    targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-prometheus-db01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      name: backend-prometheus-db01
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
      - name: backend-prometheus-db01
        image: backend-prometheus-db01
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        args:
        - '--config.file=/mnt/etc/config.yaml'
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: configmap-prometheus-config01
          mountPath: /mnt/etc/
        - name: data-volume
          mountPath: /mnt/data/
        - name: secrets-volume
          mountPath: /var/run/secrets
      volumes:
      - name: configmap-prometheus-config01
        configMap:
          name: configmap-prometheus-config01
      - name: data-volume
        emptyDir: {}
      - name: secrets-volume
        hostPath:
          path: /var/run/secrets