apiVersion: v1
kind: Service
metadata:
  name: backend-promtail-agent01
  labels:
    app.kubernetes.io/name: promtail
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 9080
      targetPort: 9080
  selector:
    app.kubernetes.io/name: promtail
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: backend-promtail-agent01
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: promtail
  template:
    metadata:
      labels:
        app.kubernetes.io/name: promtail
    spec:
      #dnsPolicy: ClusterFirstWithHostNet
      #hostNetwork: true
      hostPID: true
      serviceAccountName: promtail
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: backend-promtail-agent01
        image: backend-promtail-agent01
        args:
        - -config.file=/etc/promtail/config-promtail.yaml
        - -config.expand-env=true
        - -client.external-labels=hostname=$(HOSTNAME)
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "125Mi"
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - containerPort: 9080
          name: http
        volumeMounts:
        - name: config-volume01
          mountPath: /etc/promtail
        - name: varlog
          mountPath: /var/log
        - name: secret-volume
          mountPath: /var/run/secrets
        - name: run
          mountPath: /run/promtail
        - name: containers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: pods
          mountPath: /var/log/pods
          readOnly: true
      volumes:
      - name: config-volume01
        configMap:
          name: configmap-promtail-config01
      - name: varlog
        hostPath:
          path: /var/log
      - name: secret-volume
        hostPath:
          path: /var/run/secrets
      - name: run
        hostPath:
          path: /run/promtail
      - name: containers
        hostPath:
          path: /var/lib/docker/containers
      - name: pods
        hostPath:
          path: /var/log/pods