apiVersion: v1
kind: Service
metadata:
  name: mimir-01
  labels:
    app.kubernetes.io/name: mimir
spec:
  ports:
  - name: tcp01
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: mimir
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mimir-01-headless
  labels:
    app.kubernetes.io/name: mimir
spec:
  ports:
  - name: tcp01
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: mimir
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mimir-01-data
  labels:
    app.kubernetes.io/name: mimir
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimir-01
  labels:
    app.kubernetes.io/name: mimir
spec:
  minReadySeconds: 10
  replicas: 3
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: mimir
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mimir
    spec:
      containers:
      - args:
        - -config.file=/etc/mimir/config-mimir.yaml
        - -config.expand-env
        name: mimir-01
        image: mimir-01
        imagePullPolicy: Always
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        ports:
        - containerPort: 8080
          name: tcp01
          protocol: TCP
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef: 
              name: kustomize-secret-minio-key
              key: minio_access_key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: kustomize-secret-minio-key
              key: minio_secret_key
        volumeMounts:
        - mountPath: /etc/mimir
          name: configmap-mimir-config01
        - mountPath: /data/mimir
          name: mimir-01-data
        - mountPath: /tmp
          name: tmp
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      restartPolicy: Always
      terminationGracePeriodSeconds: 4800
      volumes:
      - name: configmap-mimir-config01
        configMap:
          name: configmap-mimir-config01
          defaultMode: 420
      - name: mimir-01-data
        persistentVolumeClaim:
          claimName: mimir-01-data
      - emptyDir: {}
        name: tmp