apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: blackbox-exporter
  name: backend-blackbox-exporter01
spec:
  type: ClusterIP
  ports:
  - port: 9115
    targetPort: 9115
    protocol: TCP
  selector:
    app.kubernetes.io/name: blackbox-exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: blackbox-exporter
  name: backend-blackbox-exporter01
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: blackbox-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: blackbox-exporter
    spec:
      containers:
      - name: backend-blackbox-exporter01
        image: bakend-blackbox-exporter01
        ports:
        - containerPort: 9115
        args:
        - '--config.file=/config/config-blackbox-exporter.yaml'
        volumeMounts:
        - name: config-volume
          mountPath: /config
      volumes:
      - name: config-volume
        configMap:
          name: configmap-blackbox-exporter-config01