apiVersion: v1
kind: Service
metadata:
  name: backend-manager01
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9093'
spec:
  selector: 
    app: alertmanager
  type: NodePort  
  ports:
    - port: 9093
      targetPort: 9093
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-manager01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      name: alertmanager
      labels:
        app: alertmanager
    spec:
      containers:
      - name:  backend-manager01
        image:  backend-manager01
        args:
          - "--config.file=/mnt/alertmanager/config-alertmanager.yaml"
          - "--storage.path=/mnt/data"
        ports:
        - name: alertmanager
          containerPort: 9093
        resources:
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: 1
              memory: 1Gi
        volumeMounts:
        - name: configmap-alertmanager-volume
          mountPath: /mnt/alertmanager
        - name: alertmanager
          mountPath: /mnt/data
      volumes:
      - name: configmap-alertmanager-volume
        configMap:
          name: configmap-alertmanager-config01
      - name: alertmanager
        emptyDir: {}