apiVersion: v1
kind: Service
metadata:
  name: backend-alertmanager01
  labels:
    app.kubernetes.io/name: alertmanager
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9093'
spec:
  selector: 
    app.kubernetes.io/name: alertmanager
  type: NodePort  
  ports:
    - port: 9093
      targetPort: 9093
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-alertmanager01
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: alertmanager
  template:
    metadata:
      name: alertmanager
      labels:
        app.kubernetes.io/name: alertmanager
    spec:
      containers:
      - name:  backend-alertmanager01
        image:  backend-alertmanager01
        args:
          - "--config.file=/mnt/alertmanager/config-alertmanager.yaml"
          - "--storage.path=/mnt/data"
        ports:
        - name: alertmanager
          containerPort: 9093
        resources:
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: 1000m
              memory: 1Gi
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: configmap-alertmanager-volume
          mountPath: /mnt/alertmanager
        - name: alertmanager
          mountPath: /mnt/data
      volumes:
      - name: configmap-alertmanager-volume
        configMap:
          name: configmap-alertmanager-config01
      - name: alertmanager
        emptyDir: {}