apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
namePrefix: monitoring-
nameSuffix: "-001"
secretGenerator:
- name: kustomize-password
  files:
  - password=password.txt
  - token=token.txt
generatorOptions:
  disableNameSuffixHash: true