{
 "title": "Loki:NamespaceLogs",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "info",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time( {namespace=\"$namespace\"} |~ \"info\" [5m])"
    }
   ]
  },
  {
   "title": "warning",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "count_over_time( {namespace=\"$namespace\"} |~ \"warning\" [5m])"
    }
   ]
  },
  {
   "title": "alert",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count_over_time( {namespace=\"$namespace\"} |~ \"alert\" [5m])"
    }
   ]
  },
  {
   "title": "error",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "count_over_time( {namespace=\"$namespace\"} |~ \"error\" [5m])"
    }
   ]
  },
  {
   "title": "crit",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "count_over_time( {namespace=\"$namespace\"} |~ \"crit\" [5m])"
    }
   ]
  },
  {
   "title": "info_Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\"} |~ \"info\""
    }
   ]
  },
  {
   "title": "warning_Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\"} |~ \"warning\""
    }
   ]
  },
  {
   "title": "alart_Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\"} |~ \"alert\""
    }
   ]
  },
  {
   "title": "error_Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\"} |~ \"error\""
    }
   ]
  },
  {
   "title": "crit_Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\"} |~ \"crit\""
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\"}"
    }
   ]
  }
 ]
}