{
 "title": "Telegraf:KubernetesResources",
 "description": "InfluxDB dashboards for telegraf metrics",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   { "name": "inter", "label": "Sampling", "query": "10s,30s,1m,2m,5m,10m,30m,1h" },
   {
    "name": "host",
    "label": "host",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: \"${buckets}\", tag: \"host\")"
   },
   { "name": "buckets", "query": "buckets()" }
  ]
 },
 "panels": [
  { "title": "Quick overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"system\" and\r\n    r._field == \"uptime\"\r\n  )\r\n  |> aggregateWindow(every: 1m, fn: mean)",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "LA medium",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"system\" and\r\n    r._field == \"load5\"\r\n  )\r\n  |> aggregateWindow(every: 1m, fn: mean)",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Zombies",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"processes\" and\r\n  r._field == \"zombies\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)",
     "select": [
      [
       { "params": [ "zombies" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"processes\" and\r\n  r._field == \"running\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"processes\" and\r\n  r._field == \"total_threads\"\r\n)",
     "select": [
      [
       { "params": [ "total_threads" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "blocked",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"processes\" and\r\n  r._field == \"blocked\"\r\n)",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "dead",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"processes\" and\r\n  r._field == \"dead\"\r\n)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "idle",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"processes\" and\r\n  r._field == \"idle\"\r\n)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "paging",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"processes\" and\r\n  r._field == \"paging\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ]
    }
   ]
  },
  {
   "title": "processes_unknown",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"processes\" and\r\n  r._field == \"unknown\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  { "title": "System Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "cpu_usage_core",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kubernetes_node\" and\r\n  r._field == \"cpu_usage_core_nanoseconds\" //and\r\n  //r.host == \"${host}\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "CPU usage_system",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kubernetes_node\" and\r\n  r._field == \"cpu_usage_nanocores\" //and\r\n  //r.host == \"${host}\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Fs_available_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kubernetes_node\" and\r\n  r._field == \"fs_available_bytes\" //and\r\n  //r.host == \"${host}\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Fs_capacity_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kubernetes_node\" and\r\n  r._field == \"fs_capacity_bytes\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Fs_used_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kubernetes_node\" and\r\n  r._field == \"fs_used_bytes\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Fs_used_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kubernetes_node\" and\r\n  r._field == \"fs_used_bytes\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Fs_used_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kubernetes_node\" and\r\n  r._field == \"fs_used_bytes\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Memory_major_page_faults",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kubernetes_node\" and\r\n  r._field == \"memory_major_page_faults\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Memory_available_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kubernetes_node\" and\r\n  r._field == \"memory_available_bytes\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Memory_rss_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kubernetes_node\" and\r\n  r._field == \"memory_rss_bytes\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Memory_usage_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kubernetes_node\" and\r\n  r._field == \"memory_usage_bytes\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Memory_working_set_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kubernetes_node\" and\r\n  r._field == \"memory_working_set_bytes\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Network_rx_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kubernetes_node\" and\r\n  r._field == \"network_rx_bytes\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Memory_usage_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kubernetes_node\" and\r\n  r._field == \"network_rx_errors\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Network_tx_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kubernetes_node\" and\r\n  r._field == \"network_tx_bytes\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Network_tx_errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kubernetes_node\" and\r\n  r._field == \"network_tx_errors\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Runtime_image_fs_available_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kubernetes_node\" and\r\n  r._field == \"runtime_image_fs_available_bytes\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Runtime_image_fs_capacity_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kubernetes_node\" and\r\n  r._field == \"runtime_image_fs_capacity_bytes\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  { "title": "Pod Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Cpu_usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kubernetes_pod_container\" and\r\n  r._field == \"cpu_usage_nanocores\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Cpu_usage_core",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kubernetes_pod_container\" and\r\n  r._field == \"cpu_usage_core_nanoseconds\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Logsfs_available_bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kubernetes_pod_container\" and\r\n  r._field == \"logsfs_available_bytes\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Memory_major_page_faults",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kubernetes_pod_container\" and\r\n  r._field == \"memory_major_page_faults\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Memory_page_faults",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kubernetes_pod_container\" and\r\n  r._field == \"memory_page_faults\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Memory_page_faults",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kubernetes_pod_container\" and\r\n  r._field == \"memory_rss_bytes\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Memory_usage_bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kubernetes_pod_container\" and\r\n  r._field == \"memory_usage_bytes\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Memory_working_set_bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kubernetes_pod_container\" and\r\n  r._field == \"memory_working_set_bytes\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Rootfs_available_bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kubernetes_pod_container\" and\r\n  r._field == \"rootfs_available_bytes\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Rootfs_used_bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kubernetes_pod_container\" and\r\n  r._field == \"rootfs_used_bytes\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Rootfs_capacity_bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kubernetes_pod_container\" and\r\n  r._field == \"rootfs_capacity_bytes\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  { "title": "Pod Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 189 } },
  {
   "title": "Rx_bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 190 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kubernetes_pod_network\" and\r\n  r._field == \"rx_bytes\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Tx_bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 190 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kubernetes_pod_network\" and\r\n  r._field == \"tx_bytes\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Tx_Rx_errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 190 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kubernetes_pod_network\" and\r\n  r._field == \"rx_errors\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    },
    {
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kubernetes_pod_network\" and\r\n  r._field == \"tx_errors\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  { "title": "Pod Volume", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 197 } },
  {
   "title": "Available_bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 198 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_irq",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "irq" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interrupts",
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kubernetes_pod_volume\" and\r\n  r._field == \"available_bytes\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Used_bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 205 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_irq",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "irq" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interrupts",
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kubernetes_pod_volume\" and\r\n  r._field == \"used_bytes\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)\r\n",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Capacity_bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 212 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_irq",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "irq" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interrupts",
     "query": "from(bucket: \"monitoring\")\r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n|> filter(fn: (r) =>\r\n  r._measurement == \"kubernetes_pod_volume\" and\r\n  r._field == \"capacity_bytes\"\r\n)\r\n|> aggregateWindow(every: 1m, fn: mean)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  }
 ]
}