apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: process-exporter
  name: bakend-process-exporter01
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: process-exporter
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: process-exporter
    spec:
      hostPID: true
      hostIPC: true
      hostNetwork: true
      enableServiceLinks: false
      serviceAccountName: prometheus
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
        - name: bakend-process-exporter01
          image: bakend-process-exporter01
          args:
            - "--procfs"
            - "/host/proc"
            - "--web.listen-address=:9256"
            - "--config.path=/config/config-process-exporter.yaml"
          ports:
            - containerPort: 9256
              name: metrics
          securityContext:
            privileged: true
          volumeMounts:
          - name: config-volume01
            mountPath: /config
          - name: proc
            mountPath: /host/proc
            readOnly: true
          env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      volumes:
      - name: config-volume01
        configMap:
          name: configmap-process-exporter-config01
      - name: proc
        hostPath:
          path: /proc