apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging-monitoring
namePrefix: staging-monitoring-
nameSuffix: "-001"
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: kustomize-secret
  files:
  - password=password.txt
  - token-telegraf=token-telegraf.txt
  - token-slack=token-slack.txt