apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana/deployment-frontend-grafana-app01.yaml
  - grafana/deployment-backend-grafana-db01.yaml
  - loki-read/deployment-frontend-loki-read01.yaml
  - loki-write/deployment-backend-loki-write01.yaml
  - loki-backend/deployment-backend-loki-backend01.yaml
  - loki-headless/service-frontend-loki-headless01.yaml
  - minio-mimir/minio-mimir-01.yaml
  - mimir/mimir-01.yaml
  - influxdb/deployment-backend-influxdb-db01.yaml
  - telegraf/daemonset-backend-agent01.yaml
  - promtail/daemonset-backend-agent01.yaml
  - prometheus/deployment-backend-prometheus-app01.yaml
  - node-exporter/daemonset-backend-node-exporter-agent01.yaml
#  - process-exporter/daemonset-backend-process-exporter01.yaml
  - blackbox-exporter/deployment-backend-blackbox-exporter01.yaml
  - alertmanager/deployment-backend-alertmanager01.yaml
  - rbac/rbac-telegraf.yaml
  - rbac/rbac-promtail.yaml
  - rbac/rbac-prometheus.yaml
  - rbac/rbac-influxdb.yaml