apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
namePrefix: monitoring-
nameSuffix: "-001"
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: kustomize-secret
  files:
  - password=password.txt
  - token-telegraf=token-telegraf.txt
configMapGenerator:
- name: configmap-alertmanager-config01
  files:
  - config-alertmanager.yaml