apiVersion: 1
datasources:
  - name: loki-datasource
    type: loki
    uid: loki-datasource
    url: http://staging-monitoring-frontend-loki-read01-001:3100
    access: proxy
    orgId: 1
    basicAuth: false
    editable: true
    isDefault: false
    version: 1

  - name: prometheus-datasource
    type: prometheus
    uid: prometheus-datasource
    url: http://staging-monitoring-backend-prometheus-db01-001:9090
    access: proxy
    orgId: 1
    basicAuth: false
    editable: true
    isDefault: false
    version: 1

  - name: mimir-datasource
    type: prometheus
    uid: mimir-datasource
    url: http://monitoring-mimir-01-001:8080/prometheus
    access: proxy
    orgId: 1
    basicAuth: false
    editable: true
    isDefault: false
    version: 1
  
  - name: influxdb-datasource
    type: influxdb
    uid: influxdb-datasource
    url: http://staging-monitoring-backend-influxdb-db01-001:8086
    access: proxy
    orgId: 1
    basicAuth: false
    editable: true
    isDefault: false
    version: 1
    jsonData:
      version: Flux
      organization: monitoring
      defaultBucket: monitoring
      tlsSkipVerify: true

  - name: alertmanager-datasource
    type: alertmanager
    uid: alertmanager-datasource
    url: http://staging-monitoring-backend-alertmanager01-001:9093
    access: proxy
    orgId: 1
    basicAuth: false
    editable: true
    isDefault: false
    version: 1
    jsonData:
      implementation: prometheus
