global:
  scrape_interval: 60s
  evaluation_interval: 60s
alerting:
   alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "monitoring-backend-alertmanager01-001:9093"
rule_files:
  - /mnt/prometheus/rules-prometheus.yaml
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets:
        - "monitoring-backend-prometheus-db01-001:9090"
  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
    - role: node
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  - job_name: 'cadvisor'
    kubernetes_sd_configs:
    - role: node
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    metrics_path: /metrics/cadvisor
  - job_name: 'node'
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - node1:9100
        - node2:9100
        - node3:9100
        - node4:9100
        - node5:9100
        - node6:9100
        - node7:9100
    relabel_configs:
    - source_labels: [__address__]
      regex: '(.*):9100'
      target_label: instance
      replacement: '$1'  
  - job_name: 'temperature-exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - node1:8000
        - node2:8000
        - node3:8000
        - node4:8000
        - node5:8000
        - node6:8000
        - node7:8000
    relabel_configs:
    - source_labels: [__address__]
      regex: '(.*):8000'
      target_label: instance
      replacement: '$1'
  - job_name: 'service'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://www.aimhighergg.com/
        - https://www.aimhighergg.com/portfolio/
        - https://www.aimhighergg.com/wiki/Tips
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "monitoring-backend-blackbox-exporter01-001:9115"
remote_write:
  - url: "http://monitoring-mimir-01-001:8080/api/v1/push"