apiVersion: v1
kind: Service
metadata:
  name: minio-loki-01
spec:
  selector:
    app.kubernetes.io/name: minio-loki
    app.kubernetes.io/component: minio
  ports:
  - name: tcp01
    port: 9000
    targetPort: 9000
    protocol: TCP
  - name: tcp02
    port: 9090
    targetPort: 9090
    protocol: TCP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-loki-01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-loki-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: minio-loki
      app.kubernetes.io/component: minio
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio-loki
        app.kubernetes.io/component: minio
    spec:
      containers:
      - name: minio-loki-01
        image: minio-loki-01
        args:
        - server
        - /data
        - --console-address
        - :9090
        ports:
        - containerPort: 9000
          name: tcp01
          protocol: TCP
        - containerPort: 9090
          name: tcp02
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minio-loki-01
