apiVersion: v1
kind: Service
metadata:
  name: minio-mimir-01
spec:
  selector:
    app.kubernetes.io/name: minio-mimir
    app.kubernetes.io/component: minio
  ports:
  - name: tcp01
    port: 9000
    targetPort: 9000
    protocol: TCP
  - name: tcp02
    port: 9090
    targetPort: 9090
    porotocol: TCP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-mimir-01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-mimir-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: minio-mimir
      app.kubernetes.io/component: minio
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio-mimir
        app.kubernetes.io/component: minio
    spec:
      containers:
      - name: minio-mimir-01
        image: minio-mimir-01
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        args:
        - server
        - /data
        - --console-address
        - :9090
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MINIO_ROOT_USER
          valuesFrom:
            secretKeyRef: 
              name: kustomize-secret
              key: minio_root_user
        - name: MINIO_ROOT_PASSWORD
          valuesFrom:
            secretKeyRef:
              name: kustomize-secret
              key: minio_root_password
        ports:
        - containerPort: 9000
          name: tcp01
          protocol: TCP
        - containerPort: 9090
          name: tcp02
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minio-mimir-01
