auth_enabled: false
ingester_client:
  grpc_client_config:
    max_send_msg_size: 33554432
    max_recv_msg_size: 33554432
ingester:
  chunk_block_size: 262144
  chunk_idle_period: 1h
  chunk_target_size: 1048576
  chunk_retain_period: 30s
  max_chunk_age: 1h 
  wal:
    dir: /data/loki/wal
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  max_transfer_retries: 0
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 8
  ingestion_burst_size_mb: 16
  per_stream_rate_limit: 5MB
  per_stream_rate_limit_burst: 15MB
  max_query_length: 2165h
  max_query_lookback: 90d
  max_cache_freshness_per_query: '10m'
schema_config:
  configs:
  - from: "2020-10-24"
    index:
      period: 24h
      prefix: index_
    object_store: filesystem
    schema: v11
    store: boltdb-shipper
server:
  http_listen_port: 3100
  http_server_read_timeout: 60s
  http_server_write_timeout: 60s
  grpc_server_max_recv_msg_size: 33554432
  grpc_server_max_send_msg_size: 33554432
  log_level: info
storage_config:
  boltdb:
    directory: /data/loki/index
  filesystem:
    directory: /data/loki/chunks
  boltdb_shipper:
    active_index_directory: /data/loki/boltdb-shipper-active
    cache_location: /data/loki/boltdb-shipper-cache
    cache_ttl: 72h         # Can be increased for faster performance over longer query periods, uses more disk space
    shared_store: filesystem
chunk_store_config:
  max_look_back_period: 2184h
table_manager:
  retention_deletes_enabled: true
  retention_period: 240h
compactor:
  shared_store: filesystem
  working_directory: /data/loki/boltdb-shipper-compactor
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
ruler:
  alertmanager_url: dev-monitoring-backend-manager01-001.testing-monitoring.svc.cluster.local:9093