global:
  scrape_interval: 60s
  evaluation_interval: 60s
alerting:
   alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "dev-monitoring-backend-alertmanager01-001:9093"
rule_files:
  - /mnt/prometheus/rules-prometheus.yaml
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets:
      - "dev-monitoring-backend-alertmanager01-001:9093"
  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
    - role: node
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  - job_name: 'cadvisor'
    kubernetes_sd_configs:
    - role: node
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    metrics_path: /metrics/cadvisor