apiVersion: v1
kind: Service
metadata:
  name: backend-influxdb-db01
  labels:
    app.kubernetes.io/name: influxdb
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8086
      targetPort: 8086
  selector:
    app.kubernetes.io/name: influxdb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-influxdb-db01
  labels:
    app.kubernetes.io/name: influxdb
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-influxdb-db01
  labels:
    app.kubernetes.io/name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: influxdb
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - influxdb
            topologyKey: "kubernetes.io/hostname"
      serviceAccountName: influxdb
      containers:
      - name: backend-influxdb-db01
        image: backend-influxdb-db01
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "200m"
            memory: "200Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        env:
        - name: DOCKER_INFLUXDB_INIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kustomize-password
              key: password
        - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: kustomize-password
              key: token   
        - name: DOCKER_INFLUXDB_INIT_MODE
          valueFrom:
            configMapKeyRef:
              name: configmap-influxdb-init01
              key: DOCKER_INFLUXDB_INIT_MODE
        - name: DOCKER_INFLUXDB_INIT_USERNAME
          valueFrom:
            configMapKeyRef:
              name: configmap-influxdb-init01
              key: DOCKER_INFLUXDB_INIT_USERNAME
        - name: DOCKER_INFLUXDB_INIT_BUCKET
          valueFrom:
            configMapKeyRef:
              name: configmap-influxdb-init01
              key: DOCKER_INFLUXDB_INIT_BUCKET
        - name: DOCKER_INFLUXDB_INIT_RETENTION
          valueFrom:
            configMapKeyRef:
              name: configmap-influxdb-init01
              key: DOCKER_INFLUXDB_INIT_RETENTION
        - name: DOCKER_INFLUXDB_INIT_ORG
          valueFrom:
            configMapKeyRef:
              name: configmap-influxdb-init01
              key: DOCKER_INFLUXDB_INIT_ORG
        ports:
        - containerPort: 8086
          name: influxdb
        volumeMounts:
        - name: backend-influxdb-data01
          mountPath: /var/lib/influxdb2
      volumes:
      - name: backend-influxdb-data01
        persistentVolumeClaim:
          claimName: backend-influxdb-db01